version: '2'
services:

  server:
    build:
      context: ./server/
    volumes:
      - ./server/:/usr/app/server
      - /usr/app/node_modules
    ports:
      - "8080:8080"
#     env_file: ./server/.env # TODO - uncomment this to auto-load your .env file!
    environment:
      - NODE_ENV=development

  client:
    build:
      context: ./client/
    volumes:
      - ./client/:/usr/app/client
      - /usr/app/node_modules
    depends_on:
      - server
    ports:
      - "3000:3000"
