name: CI_IMG_BUILD_PUSH

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: weraisedup
          password: ${{ secrets.CR_PAT }}
      -
        name: Build and push SERVER...
        uses: docker/build-push-action@v2
        with:
          context: ./server/
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/weraisedup/smorgasbord-server-${{ github.sha }}:latest
            ghcr.io/weraisedup/smorgasbord-server-${{ github.sha }}:1.0.0
      -
        name: Build and push CLIENT...
        uses: docker/build-push-action@v2
        with:
          context: ./client/
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/weraisedup/smorgasbord-client-${{ github.sha }}:latest
            ghcr.io/weraisedup/smorgasbord-client-${{ github.sha }}:1.0.0
