# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Publish Server Docker Image to GitHub Registry
        # You may pin to the exact commit or the version.
        # uses: TilBlechschmidt/gp-docker-action@f89287d44556dd7d24f76c799cd0795eeb352bcf
        uses: TilBlechschmidt/gp-docker-action@v0.2-alpha
        with:
          # GitHub token to push Docker image to GitHub Packages
          github-token: ${{ secrets.CR_PAT }}
          # Docker Image name
          image-name: ${{ github.sha }}-server
          dockerfile-path: ./server/    

      - name: Publish Client Docker Image to GitHub Registry
        # You may pin to the exact commit or the version.
        # uses: TilBlechschmidt/gp-docker-action@f89287d44556dd7d24f76c799cd0795eeb352bcf
        uses: TilBlechschmidt/gp-docker-action@v0.2-alpha
        with:
          # GitHub token to push Docker image to GitHub Packages
          github-token: ${{ secrets.CR_PAT }}
          # Docker Image name
          image-name: ${{ github.sha }}-client
          dockerfile-path: ./client/
